version: '3'

# This is a compose file for running the system locally,
# and therefore requires running microservices independently.
# There is not .env file for environment variables,
# since this is for testing and development purposes only
# For a complete setup w/ all microservices, execute the docker-compose-deploy.yml

services:
  identityStore:
    image: mongo
    restart: 'unless-stopped'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mongodb/data
  taskStore:
    image: postgres:14.1-alpine
    restart: 'unless-stopped'
    network_mode: "bridge"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  db:
    driver: local