version: '3.8'

# This is a compose file for running the system locally,
# and therefore requires running microservices independently.
# There is not .env file for environment variables,
# since this is for testing and development purposes only
# For a complete setup w/ all microservices, execute the docker-compose-deploy.yml

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: 'on-failure'
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  identityStore:
    ports:
      - '27017:27017'
    image: mongo
    restart: 'on-failure'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/mongodb/data
  identityService:
    image: identity
    build: ./identityService
    depends_on:
      - identityStore
      - rabbitmq
    ports:
      - '3002:3002'

  taskStore:
    container_name: taskStore
    image: neo4j:4.0
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_query__cache__size=0
  taskService:
    image: task
    build: ./taskService
    depends_on:
      - taskStore
      - rabbitmq
    ports:
      - '3001:3001'

  activityStore:
    image: cassandra:4.0
    network_mode: host
    volumes:
      - ./data:/cassandra/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix
  activityService:
    image: activity
    build: ./activityService
    depends_on:
      - activityStore
      - rabbitmq
    ports:
      - '3003:3003'


  frontend:
    image: frontend
    build: ./frontend
    ports:
      - "4200:80"

  gateway:
    image: gateway
    build: ./gateway
    ports:
      - '5000:5000'
