version: '3.8'

# This is a compose file for running the system locally,
# and therefore requires running microservices independently.
# There is not .env file for environment variables,
# since this is for testing and development purposes only
# For a complete setup w/ all microservices, execute the docker-compose-dev.yml

services:
  rabbitmq:
    ports:
       - '5672:5672'
       - '15672:15672'
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: 'on-failure'
    volumes:
      - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  identityStore:
    ports:
      - '27017:27017'
    image: mongo
    restart: 'on-failure'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/mongodb/data

  taskStore:
    ports:
      - '7474:7474'
      - '7687:7687'
    container_name: taskStore
    image: neo4j:4.0
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_query__cache__size=0

  activityStore:
    ports:
      - '9042:9042'
    image: cassandra:4.0
    volumes:
      - ./data:/cassandra/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix